### ISSUE TITLE
SSPI failed

### ISSUE THREAD

**Issue by justurn** [stoneharry/DBC-Editing-Workflow#1]
I set up the config for the headless export but it crashed when I run it from CLI.
It errors on attempting to connect to the MySQL server.

Loading config...
Creating MySQL connection from config.xml...
Build failed: System.Security.Authentication.AuthenticationException: A call to SSPI failed, see inner exception.
System.Security.Authentication.AuthenticationException: A call to SSPI failed, see inner exception. ---> System.ComponentModel.Win32Exception: The function requested is not supported
   --- End of inner exception stack trace ---

**Comment by stoneharry** [comment]
Are you using the headless exported attached to this repo? It's quite an old build using old versions of libraries, I think it needs recompiling.

**Comment by stoneharry** [comment]
I have just posted v2.1.0 of the spell editor which now includes a compiled updated version of the Headless Exporter. Can you give the one in that release a go please?

https://github.com/stoneharry/WoW-Spell-Editor/releases

**Comment by justurn** [comment]
That is working now, thank you!
